### ISSUE TITLE
how can i play

### ISSUE THREAD

**Issue by Maexle-38** [hawadlu/Cluedo#1]
Hello Sir,

I hope you can help me.
how can i install and play the game?

Thank you

**Comment by hawadlu** [comment]
You'll need to clone this repo. Once you've done that you'll need to compile each of the files. Once you've compiled each of the files, run the application class.

**Comment by Maexle-38** [comment]
Thank you for your anwser

I don't have much experience in programming.

I'm using Ubuntu - in every tutorial they use a ./configure it answers me "no such file or directory"

I hope you can help me.
